### PR TITLE
Enable ocp-indent to be safe-string compatible

### PR DESCRIPTION
**Pull request by jpdeplaix**

### CODE REVIEW

**Comment by nojb** [comment]
@AltGr Sorry to hijack this PR for an unrelated question (ok, maybe not completely unrelated), but what's the meaning of the different branches `rewind`, `1.5`, `master` ?

**Comment by jpdeplaix** [comment]
oh yes, I was wondering myself. I used ```rewind``` because it is the default branch but I don't understand neither what is the difference with the ```master``` branch.

**Comment by AltGr** [comment]
Thanks! It's important that `ocp-indent` still compiles with older versions of OCaml, can you confirm that it's the case ? Don't we need to at least add a dependency to `base-bytes` ?

@nojb: indeed, that should be clarified. A while ago, we started a big change that uses EOL tokens instead of relying on position information. The goal was to simplify parts of the code, in particular the printer, which is very intricated. This is the version that is used by [learn-ocaml](https://try.ocamlpro.com/learn-ocaml-demo/), but unfortunately, we ended up with too many regressions on the CLI tool, so when a release was needed, we backported the fixes to the `rewind` branch, which is currently the main branch for the tool. We're still hoping to merge back the `eol_tokens` version (current master) and iron out the issues, but have been short-manned since. I should definitely rename the branches to avoid confusion in the meantime, though.

**Comment by jpdeplaix** [comment]
You're right I forgot to depend over ```base-bytes```. It is fixed.
I just tested it with the minimal version where ```ocp-indent``` is available which is ```4.01.0``` and it works. Previous versions are not available because of ```cmdliner```.

**Comment by AltGr** [comment]
Great, thanks!

**Pull request merged**
