### PR TITLE
Jbuilder

### PR DESCRIPTION
**Pull request by rgrinberg**
Port build system to jbuilder

### CODE REVIEW

**Comment by rgrinberg** [comment]
Check out the last commit for how I handle the version stuff.

I still need to finish porting the tests.

**Comment by rgrinberg** [comment]
OK I ported the tests as well. IMO it would be a lot nicer to completely port the tests to jbuilder rules but the html reporting and the rest is a bit much to do. So for now, I just made it work as it did before.

**Comment by Leonidas-from-XIV** [comment]
Came to this repository to request porting to jbuilder because building `ocp-build` is the thing that takes the longest time to build `ocp-indent` and `jbuilder` is likely installed anyway because lots of things depend on it already.

**Comment by rgrinberg** [comment]
ping @AltGr

**Comment by AltGr** [comment]
Thanks for this!
I am a little bothered by the lack of compatibility with earlier OCaml versions... but well, since the only updates in the last years or so have been to support new OCaml features, I guess users of older OCaml versions are good with the older ocp-indent versions...

About the version mechanism, I am not strongly attached to the existing mechanism with a `VERSION` file, so if you have an idea for something cleaner with jbuilder, that's fine! As for the tests, they are quite specific and include checked-in results, an html page that can have some links to it, and manual diffs are often helpful to see what is going on... so I really prefer to keep them as they are rather than running them through jbuilder and having the results hidden in `_build/default/tests` or so: just like you did.

**Comment by AltGr** [comment]
(and sorry for the huge lag...)

**Comment by samoht** [comment]
You could also probably remove the configure file.

**Comment by rgrinberg** [comment]
Thomas Gazagnaire <notifications@github.com> writes:

> You could also probably remove the configure file.

Am I missing something? I think I got rid of it.

**Comment by rgrinberg** [comment]
Louis Gesbert <notifications@github.com> writes:

> Thanks for this!
> I am a little bothered by the lack of compatibility with earlier OCaml
> versions... but well, since the only updates in the last years or so
> have been to support new OCaml features, I guess users of older OCaml
> versions are good with the older ocp-indent versions...

4.02 was released in 2014. I believe we are being quite reasonable with
older versions. But as you said, the old versions will stay working so
that's a plus. Also, I'm fairly certain dune's overall better
portability to more users anyway :)

> About the version mechanism, I am not strongly attached to the
> existing mechanism with a `VERSION` file, so if you have an idea for
> something cleaner with jbuilder, that's fine! As for the tests, they
> are quite specific and include checked-in results, an html page that
> can have some links to it, and manual diffs are often helpful to see
> what is going on... so I really prefer to keep them as they are rather
> than running them through jbuilder and having the results hidden in
> `_build/default/tests` or so: just like you did.

Okay. One thing I'd recommend is adopting dune-release. This way we can
simply use %%VERSION%% to substitute version numbers. The way I have it
should work as it did before.

So I will leave the tests as is, but will make them runnable via dune at
least. Keep in mind though:

* The tests are likely not portable if they're in sh

* You won't get to use dune's cool promotion feature to update your test
  results :)

**Pull request merged**
