### PR TITLE
Fix indentation of local exceptions

### LINKED ISSUE #234: Local exceptions break indentation
OCaml 4.04.0 introduced `let exception ... in` but this unfortunately breaks the latest version of ocp-indent in opam.

Expected:
```ocaml
let () =
  let exception E of string in
  ()
```

Got:
```ocaml
let () =
  let exception E of string in
()
```

### PR DESCRIPTION
**Pull request by hcarty**
The implementation follows the `let module` code

Fixes #234

### CODE REVIEW

**Comment by hcarty** [comment]
Ping?

**Comment by AltGr** [comment]
Ah, yes, sorry for the lag! Saw this when I didn't have time to review, then forgot. Seems you followed the implementation for `let module`, which was the right thing to do.

Thanks a lot!

**Comment by hcarty** [comment]
You're welcome, thanks for taking the time to review and merge!

**Comment by hcarty** [comment]
@AltGr Since `master` has issues could this be cherry-picked into `rewind` for easier pinning?  Or would you prefer a PR against that branch?

**Comment by AltGr** [comment]
I cherry-picked already :)

**Comment by AltGr** [comment]
Could you rebase the `;%foo` handling, though ? It was a little less straightforward.

**Comment by hcarty** [comment]
Sure - rebase on `rewind`?

**Comment by hcarty** [comment]
#237 should be all set now for `;%foo` support under `rewind`

**Pull request merged**
